### ISSUE TITLE
constructing superpatch graph

### ISSUE THREAD

**Issue by hongdavid94** [ruitian-olivia/IGI-DL#2]
I am trying to process my H&E image to predict survival using IGI-DL

according to the README.txt, the preprocessing steps from nuclei-segmentation to nuclei features standardization are doable.

However the nuclei-graph construction step (graph_construct.py) requires visium input in the script.

How were the survival (risk scores) of the TCGA or MCO datasets assessed using IGI-DL and is it possible for me input WSI of H&E to predict risk scores?

**Comment by hongdavid94** [comment]
just to clarify, graph_construct.py and IGI_test_main.py both require the visium path as part of the script so I am confused here, aren't we supposed to predict survival risk based on H&E alone? I was trying to predict ST from H&E from IGI_test_main.py but that also requires visium data

**Comment by ruitian-olivia** [comment]
In graph_construct.py, we used the HE images from Visium data to construct nuclei-graphs. Based on each spot location in the Visium data, patches are split, and a nuclei-graph is built for each patch. The same approach can also be applied to Whole Slide Images (WSI) by first dividing them into patches and then constructing a nuclei-graph for each patch. 

Similarly, in IGI_test_main.py, we also used HE images from Visium as an example. Additionally, since Visium has spatial transcriptomics (ST) ground truth, we can evaluate the model's prediction accuracy. For WSI, if we have well-trained IGI model parameters specific to that tumor type, we can directly predict the corresponding ST for these images as well.

**Comment by hongdavid94** [comment]
Thanks for your response,

I am trying to modify the graph_construct.py so that I can fit my own HE images to represent HE images as nuclei-graph for each patch. The code seems to depend on having Visium data. For example, the python objects x_coor_tensor and y_coor_tensor are from file names 'spatial/tissue_positions_list.csv'. The y_log_tensor are from NormLog_df.csv for each patch

Could you upload the version of your code you used to construct nuclei-graph for the TCGA dataset that doesn't have ST? It is not clear how other people can reproduce that part of your research. thank you!

**Comment by hongdavid94** [comment]
an update: I tried adding my own x, y coordinates (simply the index of the patch) to each patch and it didn't throw an error in the graph_construct step... not sure if this is the right way to do it

**Comment by ruitian-olivia** [comment]
Yes, you're right. The x, y coordinates do not necessarily have to be the spot coordinates in Visium data; they can also be the x, y coordinates of different patches in the WSI. For Visium data, there is a gold standard for gene expression, but for the WSI data in TCGA, there isn't. Therefore, when constructing the Nuclei-Graph for TCGA data, the y_log_tensor attribute can be omitted.

**Comment by hongdavid94** [comment]
thank you!
